const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const REGISTER_USER = 'REGISTER_USER';
const USER_ERROR = 'USER_ERROR';
export {
  LOGIN_USER, LOGOUT_USER, REGISTER_USER, USER_ERROR,
};
